/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    screens: {
      'xs': '480px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        primary: {
          50: '#FBF1E7',
          100: '#F5E0CB',
          200: '#EBC49C',
          300: '#DDA06C',
          400: '#D08847',
          500: '#C8773D',
          600: '#A85A28',
          700: '#8A4720',
          800: '#6E381B',
          900: '#4A2512',
        },
        dark: {
          50:  '#FBF8F2',
          100: '#F4EDE1',
          200: '#E5DDD0',
          300: '#D1C4B0',
          400: '#A99A82',
          500: '#8A7D6B',
          600: '#6B5F4F',
          700: '#4A4038',
          800: '#332C26',
          900: '#2B2520',
          950: '#1C1714',
        },
        sage: {
          50:  '#F2F5EC',
          100: '#E1E9D2',
          200: '#C3D5A6',
          300: '#A0BC78',
          400: '#85A85C',
          500: '#6C8F45',
          600: '#54712F',
          700: '#3E5423',
        },
      },
      fontFamily: {
        sans: ['"Source Sans 3"', '"Open Sans"', 'system-ui', 'sans-serif'],
        serif: ['"Source Serif Pro"', '"Source Serif 4"', 'Georgia', 'Cambria', 'serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'slide-left': 'slideLeft 0.5s ease-out',
        'slide-right': 'slideRight 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { transform: 'translateY(20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideDown: { '0%': { transform: 'translateY(-20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideLeft: { '0%': { transform: 'translateX(20px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        slideRight: { '0%': { transform: 'translateX(-20px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        scaleIn: { '0%': { transform: 'scale(0.96)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        float: { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-10px)' } },
        shimmer: { '0%': { backgroundPosition: '-1000px 0' }, '100%': { backgroundPosition: '1000px 0' } },
      },
      backdropBlur: {
        xs: '2px',
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
      borderRadius: {
        'xl': '0.875rem',
        '2xl': '1rem',
      },
    },
  },
  plugins: [],
}
